### ISSUE TITLE
image quality loss

### ISSUE THREAD

**Issue by pnslfinal** [y2361547758/EbixExtract#4]
Hi,
Thank you for your development.
I just downlaoded your program and tried to extract a comic downloaded from ebookjapan.
The comic .ebix file is extracted to .jpg file successfully.
However, two problems occured.
All image file for each page is around very same size (8689/ 8641 KB). I think it's wired, since each page contains very different pictures. They should not be same size.
Second, when I carefully compared the extracted file and the image appears on ebookjapan officially reader, I can clearly find image quality loss after extraction. The resolution seems to drop, lines and details are not as clear as it appears on the official reader, and some extra noise appears.

Can it be considerded that though your program is able to extract .ebix file to .jpg file which can be use freely, but it fails to remove drm completely since there is a quality loss?

Thank you!

**Comment by y2361547758** [comment]
Each page over 8MB, that must be BMP (even the filename is .jpg and your photo viewer can read it), BMP's size is totally depend on image size.
So you had used newer official dll (or run this program in official reader's dir) when extracting.
I used to patch the dll to redirect truely raw stream amd dump .jpg, it's not hard when the patch work on C#/il part of the dll.

**Comment by pnslfinal** [comment]
I am sorry for my previous comments. The reason of that I found quality loss is because my own photo viewer provides bad viewing quality. After I switch to mpv (though it's mainly a video player) with very high rendering settings, the photos extracted look basically the same as it appears on the official reader.
While I have another questions. Based on how your program work, can it be considered that the files extracted is more like taking a screen shot but not the unpack (of course decryption) of the original book files (.ebix)? I guess that the photo files extracted are the stream ready to be rendered to be display after decoding of original format of image files inside .ebix file.
I am not very sure about this since I don't know how .ebix file to processed to finally be displayed by the official reader. However, bmp files should not be considered the original files inside book file downloaded from ebookjapan because it's too big for network traffic. Also, the total size of all the .jpg (actually .bmp) files is over 1 GB while the original .ebix files is about 130 MB.

**Comment by y2361547758** [comment]
The BMP you got is more like memory dump. Generally decoding jpg to BMP doesn't loss quality, but not encoding back.

> I used to patch the dll to redirect truely raw stream amd dump .jpg, it's not hard when the patch work on C#/il part of the dll.

There's even meta info in jpg file like Photoshop version, so I belive the original filetype is jpg.

**Comment by pnslfinal** [comment]
Thank you! Now I have a better understanding.
Talking about the original filetype, I also agree that it's very likely to .jpg. Because when I was trying with a Canvas dump script, I checked the web browser console. The temp files though were scrambled are also .jpeg. I guess they are very likely to be the same file type.
About the .jpg files I got through your extractor, I need to rename to *.bmp so that I can open them
with Photoshop or it cannot be recognized by PS with an error message pops up.
Also, will the meta data you mentioned be included to the files extracted?
If not, should it be better to export .bmp instead of .jpg?

**Comment by y2361547758** [comment]
Actually the crypto of ebj online reader is not the same, if you dump the image from network not canvas, you will get a jpg puzzle. Taking capture from canvas you can store it in any type, I have writen one script and store in png.

There's no meta data in BMP. Anyway meta data is not important if you're not doing Cyber Manhunt.

When you're going to do re-creation on them, BMP is enough, though they're too big sometime. ~~If you want to store them, just keep them ebix~~. Otherwise, I think jpg is better.

**Comment by pnslfinal** [comment]
Yes, through online reader, I got scrambled photos in jpg, just like what you said “jpg puzzle”
