### ISSUE TITLE
How to patch EbiJALibrary.dll to get raw jpg file

### ISSUE THREAD

**Issue by y2361547758** [y2361547758/EbixExtract#5]
# tools
[dnSpy](https://github.com/0xd4d/dnSpy) or others

# Find the function
Open my code/build and find EbixBook.Extract, follow it.
![ebj01](https://user-images.githubusercontent.com/20009998/77889022-c47b4180-729f-11ea-895a-9e70643e3ea1.png)

# Step
Here's origin dll looks like, the arrows are what we want. You can make breakpoint and run and watch the memory.
![ebj02](https://user-images.githubusercontent.com/20009998/77889041-cba24f80-729f-11ea-941f-6cd86bfcd0e3.png)

Right click and see the IL bytecode. You can read it easily if you know assembly.
![ebj04](https://user-images.githubusercontent.com/20009998/77889049-ce9d4000-729f-11ea-935c-70a5c58976ee.png)

Change these two line and save.
![ebj05](https://user-images.githubusercontent.com/20009998/77889056-d0670380-729f-11ea-81c0-72648487ec56.png)

Then the disassembly would look like this. Save the model.
![ebj06](https://user-images.githubusercontent.com/20009998/77889076-d957d500-729f-11ea-86cf-285deab1ce39.png)

Run my program and get raw jpg in ebix!

**Comment by pnslfinal** [comment]
I followed your steps while I still have BMPs.

**Comment by pnslfinal** [comment]
I compared your last screenshot (after modification to output raw jpg in this issue) of code for Extract(int) is basically the same to your release 2.0, and also the same to my own modification which followed your instructions here.
Of course, I got BMP files under .jpg suffix like the original version of your program.

**Comment by pnslfinal** [comment]
Sorry for my confusing comments. There might be some mistakes when I was doing. But I have tried a few times doing what is posted here and still got bmp files.
therefore, could you please upload your dll that modified to ouput raw jpg?
thank you!

**Comment by MI2-2** [comment]
Is this patch still valid for Ver 1.1.2?

**Comment by awh-tokyo** [comment]
I can't even get the un-patched DLL to initialize for 1.1.2.
