### ISSUE TITLE
Build Enviornment

### ISSUE THREAD

**Issue by perrinaz** [y2361547758/EbixExtract#8]
I know this might be basic but...

What does one need to build main.exe?  Where does "csc" come from?  I mean, I know it's the C# compiler but do we install Visual Studio or DotNet (current version is 5, I think) or I think it's called Visual Code or some open source alternative or.. or... etc.

G

**Comment by y2361547758** [comment]
I use csc from Visual Studio environment, .net (not .net core) should work

**Comment by perrinaz** [comment]
> I use csc from Visual Studio environment, .net (not .net core) should work

Kewl I got it!  Now I have to figure out what to do because some (not all) of the magazines are coming out as BMPs...
